### ISSUE TITLE
NotSerializableException Spliterators$1Adapter

### ISSUE THREAD

**Issue by martinmosegaard** [cloudbees/groovy-cps#111] opened 2020-10-13 13:07 UTC
Seems very similar to https://github.com/cloudbees/groovy-cps/issues/105 

Seen in a declarative Jenkins pipeline that uses parallel stages. The issue is not reproducible, but transient and happens once in a while.
```
23:02:03  an exception which occurred:
23:02:03  	in field com.cloudbees.groovy.cps.impl.ForInLoopBlock$ContinuationImpl.itr
23:02:03  	in object com.cloudbees.groovy.cps.impl.ForInLoopBlock$ContinuationImpl@fa00c69
23:02:03  	in field com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.target
23:02:03  	in object com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl@de9259b
23:02:03  	in field com.cloudbees.groovy.cps.impl.LoopBlockScopeEnv.continue_
23:02:03  	in object com.cloudbees.groovy.cps.impl.LoopBlockScopeEnv@32cc355d
23:02:03  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
23:02:03  	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@1310e23a
23:02:03  	in field com.cloudbees.groovy.cps.impl.CallEnv.caller
23:02:03  	in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@7e3705bf
23:02:03  	in field com.cloudbees.groovy.cps.Continuable.e
23:02:03  	in object org.jenkinsci.plugins.workflow.cps.SandboxContinuable@150491f0
23:02:03  	in field org.jenkinsci.plugins.workflow.cps.CpsThread.program
23:02:03  	in object org.jenkinsci.plugins.workflow.cps.CpsThread@5d77bcdc
23:02:03  	in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.threads
23:02:03  	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@7babc0ed
23:02:03  	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@7babc0ed
23:02:03  Also:   an exception which occurred:
23:02:03  	in field com.cloudbees.groovy.cps.impl.ForInLoopBlock$ContinuationImpl.itr
23:02:03  	in object com.cloudbees.groovy.cps.impl.ForInLoopBlock$ContinuationImpl@fa00c69
23:02:03  	in field com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.target
23:02:03  	in object com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl@de9259b
23:02:03  	in field com.cloudbees.groovy.cps.impl.LoopBlockScopeEnv.continue_
23:02:03  	in object com.cloudbees.groovy.cps.impl.LoopBlockScopeEnv@32cc355d
23:02:03  	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
23:02:03  	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@3d77650f
23:02:03  	in field com.cloudbees.groovy.cps.impl.CallEnv.caller
23:02:03  	in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@4efb1727
23:02:03  	in field com.cloudbees.groovy.cps.Continuable.e
23:02:03  	in object org.jenkinsci.plugins.workflow.cps.SandboxContinuable@150491f0
23:02:03  	in field org.jenkinsci.plugins.workflow.cps.CpsThread.program
23:02:03  	in object org.jenkinsci.plugins.workflow.cps.CpsThread@5d77bcdc
23:02:03  	in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.threads
23:02:03  	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@7babc0ed
23:02:03  	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@7babc0ed
23:02:03  	Caused: java.io.NotSerializableException: java.util.Spliterators$1Adapter
23:02:03  Also:   org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.cancel(CpsBodyExecution.java:253)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStepExecution.stop(ParallelStepExecution.java:74)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.checkAllDone(ParallelStep.java:151)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.onFailure(ParallelStep.java:138)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:361)
23:02:03  		at com.cloudbees.groovy.cps.impl.ThrowBlock$1.receive(ThrowBlock.java:68)
23:02:03  		at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
23:02:03  		at com.cloudbees.groovy.cps.Next.step(Next.java:83)
23:02:03  		at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
23:02:03  		at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
23:02:03  		at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
23:02:03  		at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
23:02:03  		at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
23:02:03  Also:   org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.cancel(CpsBodyExecution.java:253)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStepExecution.stop(ParallelStepExecution.java:74)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.checkAllDone(ParallelStep.java:151)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.onFailure(ParallelStep.java:138)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:361)
23:02:03  		at com.cloudbees.groovy.cps.impl.ThrowBlock$1.receive(ThrowBlock.java:68)
23:02:03  		at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
23:02:03  		at com.cloudbees.groovy.cps.Next.step(Next.java:83)
23:02:03  		at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
23:02:03  		at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
23:02:03  		at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
23:02:03  		at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
23:02:03  		at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
23:02:03  		at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
23:02:03  Caused: java.io.NotSerializableException: java.util.Spliterators$1Adapter
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:926)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
23:02:03  	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
23:02:03  	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
23:02:03  	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
23:02:03  	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
23:02:03  	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
23:02:03  	at java.util.concurrent.ConcurrentSkipListMap.writeObject(ConcurrentSkipListMap.java:1437)
23:02:03  	at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source)
23:02:03  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:02:03  	at java.lang.reflect.Method.invoke(Method.java:498)
23:02:03  	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callWriteObject(JDKSpecific.java:156)
23:02:03  	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:191)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1028)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
23:02:03  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
23:02:03  	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
23:02:03  	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
23:02:03  	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.lambda$writeObject$0(RiverWriter.java:144)
23:02:03  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:237)
23:02:03  	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.writeObject(RiverWriter.java:143)
23:02:03  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:553)
23:02:03  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:530)
23:02:03  	at org.jenkinsci.plugins.workflow.cps.CpsStepContext$3.onSuccess(CpsStepContext.java:555)
23:02:03  	at org.jenkinsci.plugins.workflow.cps.CpsStepContext$3.onSuccess(CpsStepContext.java:549)
23:02:03  	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:917)
23:02:03  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
23:02:03  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
23:02:03  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23:02:03  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:136)
23:02:03  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
23:02:03  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
23:02:03  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
23:02:03  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23:02:03  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23:02:03  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23:02:03  	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gcarpenter-chain** [comment] 2020-10-14 07:54
Thanks for the response, @martinmosegaard is away for the rest of the week, but I'm also looking at the same issue.

> If your PIpeline does not use `Spliterator`, then maybe you are interacting with some code that uses it internally. Either way it would be helpful to see a minimal form of your Pipeline, essentially we only need to see the `for(... in ...)` statements and any statements related to defining the variable being iterated over.

We don't use `Spliterator` or any `for(... in ...)` statements explicitly in the pipeline, is there anything likely to be generating the implicitly? I can look at sanitising the Jenkinsfile, but want to try not to remove anything relevant.

**Comment by dwnusbaum** [comment] 2020-10-14 14:22
> We don't use Spliterator or any for(... in ...) statements explicitly in the pipeline, is there anything likely to be generating the implicitly?

It's technically possible that something could be using `Spliterator` or `for (... in ...)` loops implicitly behind the scenes, but I am not aware of anything like that. Did you check any shared libraries used by your Pipelines as well as any scripts the Pipeline loads using the `load` step? If you still don't see anything, I guess just post as much of your Jenkinsfile as possible and maybe we'll be able to figure out what is happening.

**Comment by gcarpenter-chain** [comment] 2020-10-16 10:41
I've attached a sanitised version of the pipeline in question and some shared functions.
Pretty much all of the logic has  been replaced, but I've tried to keep everything related to looping constructs, and the structure is accurate (also included a screenshot of the pipeline layout).
Didn't manage to repro the error with the included version however, though given timing might well be a factor that may not be surprising. Let us know if there's anything else of use we can pass on.

<img width="1485" alt="Screenshot 2020-10-16 at 11 34 03" src="https://user-images.githubusercontent.com/52927626/96248560-a3601100-0fa3-11eb-8bc1-f6f0d24f1664.png">

[Jenkins.zip](https://github.com/cloudbees/groovy-cps/files/5390926/Jenkins.zip)

**Comment by martinmosegaard** [comment] 2020-11-06 13:28
@dwnusbaum We do have uses of collection functions like `each` and `collect`. Would they be related?

**Comment by martinmosegaard** [comment] 2020-11-06 13:46
@gcarpenter-chain I found a use of `for ... in` now in a shared library function:
```
for (comment in pullRequest.comments) {
```
where `pullRequest` is provided by https://github.com/jenkinsci/pipeline-github-plugin AFAIK

**Comment by martinmosegaard** [comment] 2020-11-06 14:25
@dwnusbaum We will try rewriting the use of `for ... in` to use a collection method instead. But if you have any insights into how or why `for` loops are using Spliterators and collection methods are not, that would be helpful :)

**Comment by dwnusbaum** [comment] 2020-11-06 14:50
The problem comes from the way that [`PullRequestGroovyObject.getComments`](https://github.com/jenkinsci/pipeline-github-plugin/blob/f8c080f9e876a34986ba70ba43aa1f664adc22ca/src/main/java/org/jenkinsci/plugins/pipeline/github/PullRequestGroovyObject.java#L369) is implemented in that plugin using `Stream.iterator`, which is not one of the special cases handled by [`IteratorHack`](https://github.com/jenkinsci/workflow-cps-plugin/blob/a5f0305cee615e2fef2eb45cbc577cc2f335ae1f/src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java) in Pipeline: Groovy plugin, so the call is not intercepted and replaced with a serializable iterator. In this case, I do not think it would matter what kind of loop you use, the result of that method will always be unserializable. `for ... in` loops are just one way that the iterator ends up being serialized.

One fix would be to send a PR to that plugin to update that method and others to collect the stream into a `List` and return that instead of `Stream.iterator`. A simple fix on your side would be to try calling `PullRequestGroovyObject.getComments` in a `@NonCPS` method and converting the result into a regular Groovy list that you return from the method and can then use however you want in your Pipeline (assuming the various other methods in that plugin do not have any similar issues). It may also be possible to fix this in `IteratorHack` by adding an overload that handles `BaseStream`, but I'm not 100% sure.

**Comment by martinmosegaard** [comment] 2020-11-09 08:26
Thanks @dwnusbaum , that is really helpful.

**Comment by jayceebernardino** [comment] 2021-05-03 21:33
We are also in a similar situation using `pipeline-github-plugin`. @martinmosegaard Did you end up resolving this issue?

**Comment by martinmosegaard** [comment] 2021-05-04 06:28
@jayceebernardino Yes, we had a method that called `pullRequest.comments`. We added a `@NonCPS` annotation to that method and we stored the result in a serializable ArrayList. Like this:

```
@NonCPS
def getPrComments() {
  ArrayList comments = pullRequest.comments.toList()
  return comments
}
```

**Comment by dwnusbaum** [comment] 2022-11-04 17:31
Given that this turned out to be caused by a problem in https://github.com/jenkinsci/pipeline-github-plugin, I am closing this issue.

**Closed by dwnusbaum** 2022-11-04 17:31 UTC
